[package]
name = "eom"
version = "0.9.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Configurable ODE/PDE solver"
documentation = "https://docs.rs/eom/"
repository = "https://github.com/termoshtt/eom"
keywords = ["ndarray", "ode", "pde"]
categories    = ["algorithms", "science"]
license = "MIT"
readme = "README.md"

[dependencies]
num-traits = "0.1"
num-complex = "0.1"
derive-new = "0.5"
ndarray = "0.11"
ndarray-linalg = { version = "0.9", features = ["intel-mkl"] }
fftw = { version = "0.4", features = ["intel-mkl"], default-features = false }
